= Overview
:icons: font
:toc:
:toclevels: 4
:toc-placement!:
:stylesdir: css/
:stylesheet: gradle-defaults.css

toc::[]

// tag::body[]
== Language Support

=== Java

:leveloffset: +3

include::java-plugin.adoc[]

include::lombok-plugin.adoc[]

include::checker-framework-plugin.adoc[]

:leveloffset: -1

include::groovy-plugin.adoc[]

include::scala-plugin.adoc[]

include::kotlin-plugin.adoc[]


:leveloffset: 0

== Publishing & Releasing

:leveloffset: +2

include::gh-pages-plugin.adoc[]

include::license-plugin.adoc[]

include::release-plugin.adoc[]

include::maven-publish-plugin.adoc[]

=== BinTray

If https://github.com/bintray/gradle-bintray-plugin[`com.jfrog.bintray`] is applied and `bintrayUser` and `bintrayKey` properties are set on the project, then the following configuration is set in addition to any that the build file explicitly configures:

If `defaults.bintrayLabels` includes `gradle`, the `gradle-plugin` attribute is set to support the Gradle plugin portal for any plugin IDs in `src/main/resources`.

The `main` publication from "Maven Publishing" is published to the BinTray repository.

The BinTray project is configured with information from the project and link:dokka/gradle-defaults/com.mooregreatsoftware.gradle.defaults/-defaults-extension/index.html[the "defaults" extension, see its Javadoc].


:leveloffset: 0

== Development

=== IntelliJ IDEA

Applies the `idea` plugin.

* Initializes Git as the VCS
* Sets the language level to `defaults.compatibilityVersion`
* Code formatting set to reasonable/consistent standards

:leveloffset: 0

== Opinionated Defaults

:leveloffset: +2

include::defaults-plugin.adoc[]

// end::body[]
